ARG BEATS_VERSION=6.7.2
ARG GO_VERSION=1.10.8
ARG GO_PLATFORM=linux-amd64
ARG BEAT_NAME=filebeat
FROM golang:${GO_VERSION} as builder

ARG BEATS_VERSION

WORKDIR /go/src/github.com/alazyer/beats-processors

COPY . .
RUN go get -d ./...

RUN go build -buildmode=plugin -o processors-modify-fields.so

FROM docker.elastic.co/beats/filebeat:${BEATS_VERSION}

USER root
RUN mkdir -p /usr/share/filebeat/plugins/
COPY --from=builder /go/src/github.com/alazyer/beats-processors/processors-modify-fields.so /usr/share/filebeat/plugins/
RUN chown -R filebeat:filebeat /usr/share/filebeat/plugins/
USER filebeat

CMD ["filebeat", "-e", "--plugin", "/usr/share/filebeat/plugins/processors-modify-fields.so", "-v"]